version: '20.10.13'
services:
  bookmark-db:
    image: postgres:14
    ports:
      - 5000:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nest
    networks:
      - bookmark
networks:
  bookmark:
